import {useId,useState,type ReactNode,type ComponentProps} from 'react';
import {Search,ArrowRight,ChevronRight,Info,AlertTriangle,CheckCircle2,FolderOpen,X,LoaderCircle,ShieldAlert} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';import {Skeleton} from '@/components/ui/skeleton';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell,TableCaption} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Pagination,PaginationContent,PaginationItem,PaginationLink} from '@/components/ui/pagination';
import {Link} from '@/lib/router';import {useStore} from '@/lib/store';import {STAGES,STAGE_COLORS,money,stageMetrics,type StageValues} from '@/lib/domain';
export function Btn({className='',secondary=false,...p}:ComponentProps<typeof Button>&{secondary?:boolean}){return <Button className={'btn '+(secondary?'btn-outline ':'')+className} {...p}/>;}
export function Badge({children,tone}:{children:ReactNode;tone?:string}){const s=String(children);const kind=tone??(/Selesai|Lunas|Lengkap|Aktif|Disetujui|Dirilis/.test(s)?'success':/Tinggi|Lewat|Gagal|Ditolak/.test(s)?'danger':/Menunggu|Sedang|Sebagian|Draf|Ditinjau/.test(s)?'warning':'neutral');return <span className={'status-badge '+kind}><span className="status-dot"/>{children}</span>;}
export function Field({label,hint,error,multiline=false,...p}:(ComponentProps<typeof Input>&{label:string;hint?:string;error?:string;multiline?:boolean})){const id=useId();return <div className="field"><label htmlFor={id}>{label}{p.required&&<span className="required"> *</span>}</label>{multiline?<Textarea id={id} aria-invalid={!!error} aria-describedby={hint||error?id+'-help':undefined} {...p as ComponentProps<typeof Textarea>}/>:<Input id={id} aria-invalid={!!error} aria-describedby={hint||error?id+'-help':undefined} {...p}/>} {(hint||error)&&<p id={id+'-help'} className={error?'field-error':'field-hint'}>{error||hint}</p>}</div>;}
export function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[]}){const id=useId();const mapped=options.map(o=>typeof o==='string'?{value:o,label:o}:o);return <div className="choice"><label htmlFor={id}>{label}</label><Select value={value} onValueChange={v=>v!==null&&onChange(v)}><SelectTrigger id={id} className="select-control"><SelectValue>{mapped.find(o=>o.value===value)?.label??value}</SelectValue></SelectTrigger><SelectContent>{mapped.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;}
export function Check({label,checked,onChange,disabled=false}:{label:string;checked:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){const id=useId();return <label className="check-row" htmlFor={id}><Checkbox id={id} checked={checked} disabled={disabled} onCheckedChange={onChange}/><span>{label}</span></label>;}
export function SearchBox({value,onChange,placeholder='Cari…'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="search-box"><Search size={17}/><Input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button onClick={()=>onChange('')} aria-label="Hapus pencarian"><X size={14}/></button>}</div>;}
export function Notice({children,tone='info'}:{children:ReactNode;tone?:string}){return <div className={'inline-notice '+tone} role={tone==='danger'?'alert':'status'}>{tone==='danger'?<AlertTriangle size={18}/>:tone==='success'?<CheckCircle2 size={18}/>:<Info size={18}/>}<div>{children}</div></div>;}
export function PageHeading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<div className="heading-actions">{action}</div>}</div>;}
export function Panel({title,subtitle,action,children,className=''}:{title?:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={'panel '+className}>{title&&<header className="panel-header"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</header>}{children}</section>;}
export function EmptyView({title='Belum ada data',description='Data yang cocok belum tersedia.',action}:{title?:string;description?:string;action?:ReactNode}){return <Empty className="empty-view"><EmptyHeader><FolderOpen size={36} strokeWidth={1.2}/><EmptyTitle className="empty-title">{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{action}</Empty>;}
export function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode}){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="cove-dialog" showCloseButton={false}><div className="overlay-heading"><DialogTitle>{title}</DialogTitle><DialogClose render={<Button variant="ghost" className="icon-button" aria-label="Tutup dialog"/>}><X size={20}/></DialogClose></div><DialogDescription>{description??'Formulir entitas dan operasional komersial.'}</DialogDescription>{children}</DialogContent></Dialog>;}
export function Drawer({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){return <Sheet open={open} onOpenChange={v=>!v&&onClose()}><SheetContent className="cove-drawer" showCloseButton={false}><div className="overlay-heading"><SheetTitle>{title}</SheetTitle><SheetClose render={<Button variant="ghost" className="icon-button" aria-label="Tutup detail"/>}><X/></SheetClose></div><SheetDescription>Detail entitas proyek dan riwayat data tersinkronisasi.</SheetDescription>{children}</SheetContent></Sheet>;}
export function TabSet({items,value,onChange}:{items:{id:string;label:string;content:ReactNode}[];value:string;onChange:(v:string)=>void}){return <Tabs value={value} onValueChange={v=>onChange(String(v))}><div className="tabs-scroll"><TabsList variant="line" className="cove-tabs">{items.map(i=><TabsTrigger key={i.id} value={i.id}>{i.label}</TabsTrigger>)}</TabsList></div>{items.map(i=><TabsContent key={i.id} value={i.id}>{i.content}</TabsContent>)}</Tabs>;}
export function DataTable({headers,rows,caption,paginate=6}:{headers:string[];rows:ReactNode[][];caption:string;paginate?:number}){const [page,setPage]=useState(1);const max=Math.max(1,Math.ceil(rows.length/paginate));const current=Math.min(page,max);return <><div className="table-hint">Glisir tabel untuk melihat seluruh kolom.</div><Table className="cove-table"><TableCaption className="sr-only">{caption}</TableCaption><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((current-1)*paginate,current*paginate).map((r,i)=><TableRow key={i}>{r.map((v,j)=><TableCell key={j}>{v}</TableCell>)}</TableRow>)}</TableBody></Table>{rows.length===0&&<EmptyView title="Tidak ada hasil" description="Coba ubah pencarian atau filter Anda."/>}<div className="table-footer"><span>{rows.length?((current-1)*paginate+1)+'–'+Math.min(current*paginate,rows.length):'0'} dari {rows.length} data</span>{max>1&&<Pagination><PaginationContent>{Array.from({length:max},(_,i)=><PaginationItem key={i}><PaginationLink href={'?page='+(i+1)} aria-label={'Halaman '+(i+1)} isActive={current===i+1} onClick={e=>{e.preventDefault();setPage(i+1);}}>{i+1}</PaginationLink></PaginationItem>)}</PaginationContent></Pagination>}</div></>;}
export function StageStrip({values,projectId='p1',compact=false}:{values:StageValues;projectId?:string;compact?:boolean}){const m=stageMetrics(values);return <div>{m.invalid&&<Notice tone="danger">Perlu rekonsiliasi. Ada tahap yang melebihi nilai sebelumnya.</Notice>}<div className={'stage-strip '+(compact?'compact':'')}>{STAGES.map((s,i)=><Link key={s} href={'/projects/'+projectId+'?tab=progress&stage='+i} className="stage-cell"><div><span style={{background:STAGE_COLORS[i]}}/>{s}</div><strong>{money(values[i],true)}</strong><div className="stage-track"><span style={{width:(values[0]?Math.min(100,values[i]/values[0]*100):0)+'%',background:STAGE_COLORS[i]}}/></div></Link>)}</div><p className="footnote">Nilai kumulatif · IDR · 8 Sep 2026 · Tidak dijumlahkan antar-tahap</p></div>;}
export function StateBoundary({children}:{children:ReactNode}){const {state,setState}=useStore();if(state==='loading')return <Panel><div className="state-loading" role="status"><LoaderCircle className="spin"/> Memuat data…{[1,2,3,4].map(i=><Skeleton key={i} className="h-16 w-full rounded-lg"/>)}<Btn secondary onClick={()=>setState('normal')}>Selesaikan pemuatan</Btn></div></Panel>;if(state==='error'||state==='denied')return <Panel><EmptyView title={state==='error'?'Data belum berhasil dimuat':'Anda belum memiliki akses'} description={state==='error'?'Koneksi server terputus. Filter dan konteks Anda tetap tersimpan.':'Hubungi pengelola perusahaan untuk meminta akses yang sesuai.'} action={state==='error'?<Btn onClick={()=>setState('normal')}>Coba lagi</Btn>:<Link className="btn" href="/support">Hubungi pengelola <ArrowRight/></Link>}/></Panel>;if(state==='empty')return <Panel><EmptyView title="Mulai dari satu proyek." description="Masukkan kontrak dan data progres untuk melihat bagian yang perlu ditindaklanjuti." action={<Link className="btn" href="/onboarding/project">Siapkan proyek pertama <ArrowRight/></Link>}/></Panel>;return <>{state==='stale'&&<Notice tone="warning">Data terakhir 7 Sep 2026. Periksa pembaruan sebelum mengambil keputusan. <button className="text-link" onClick={()=>setState('normal')}>Muat ulang</button></Notice>}{state==='conflict'&&<Notice tone="warning">Data ini diperbarui oleh anggota tim lain. <button className="text-link" onClick={()=>setState('normal')}>Muat versi terbaru</button></Notice>}{children}</>;}
export function Denied({text='Tindakan ini memerlukan izin pengelola perusahaan.'}:{text?:string}){return <Notice><ShieldAlert size={18}/>{text} <Link className="text-link" href="/support">Hubungi pengelola <ChevronRight size={14}/></Link></Notice>;}
